site_name: browsix
site_url: https://mathiaspaulenko.github.io/browsix/
repo_url: https://github.com/MathiasPaulenko/browsix
repo_name: MathiasPaulenko/browsix

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Installation: install.md
  - Commands: commands.md
  - Multi: multi.md
  - Backends: backends.md
  - Raw Protocol: raw.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
