"""Type stubs for bidiwave package (v2.0.0)."""

from collections.abc import Callable
from typing import Any

class Subscription:
    """Type stub for event subscription handle."""

    def unsubscribe(self) -> None: ...

class ClientConfig:
    """Type stub for ClientConfig."""

    def __init__(
        self,
        timeout: float = ...,
        max_retries: int = ...,
        retry_delay: float = ...,
        retry_backoff: float = ...,
        log_level: str = ...,
    ) -> None: ...

class BrowsingContext:
    """Type stub for BrowsingContext (create_context result)."""

    id: str
    user_context: str | None
    client: Any

class InterceptResult:
    """Type stub for InterceptResult (add_intercept result)."""

    intercept: str

class BiDiClient:
    """Type stub for BiDiClient."""

    session: Any
    browsing: Any
    script: Any
    network: Any
    storage: Any
    permissions: Any
    emulation: Any
    preload: Any
    input: Any
    cdp: Any
    _connection: Any

    @classmethod
    async def connect(
        cls, url: str, config: ClientConfig | None = ...
    ) -> BiDiClient: ...

    async def close(self) -> None: ...
    async def send_command(
        self, method: str, params: dict[str, Any] | None = ...
    ) -> dict[str, Any]: ...
    def off(self, subscription: Subscription) -> None: ...

    # Event subscription helpers (synchronous in v2.x)
    def on(self, event_type: str, handler: Callable[..., Any]) -> Subscription: ...
    def on_log_entry(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_navigation_started(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_navigation_committed(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_navigation_completed(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_navigation_failed(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_navigation_aborted(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_dom_content_loaded(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_load(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_request(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_response(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_response_started(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_auth_required(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_context_created(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_context_destroyed(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_download_will_begin(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_download_end(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_user_prompt_opened(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_user_prompt_closed(self, handler: Callable[..., Any]) -> Subscription: ...
    def on_disconnect(self, handler: Callable[..., Any]) -> None: ...
    def on_reconnect(self, handler: Callable[..., Any]) -> None: ...

    # Dialog helpers
    async def set_auto_prompt(self, accept: bool = True, user_text: str | None = None) -> None: ...
    async def disable_auto_prompt(self) -> None: ...


class Cookie:
    """Type stub for BiDiCookie."""

    def __init__(
        self,
        name: str = ...,
        value: str = ...,
        domain: str = ...,
        path: str = ...,
        **kwargs: Any,
    ) -> None: ...


__version__: str
