"""Unit tests for BackendManager."""

from __future__ import annotations

from browsix.backend.base import AbstractBackend
from browsix.backend.manager import BackendManager
from browsix.exceptions import BackendNotAvailableError, BackendNotSupportedError


class FakeBackend(AbstractBackend):
    """Fake backend for testing."""

    async def launch(self, options): ...
    async def close(self): ...
    async def navigate(self, url, wait=None): ...
    async def screenshot(self, params): ...
    async def screenshot_selector(self, selector, format="png", quality=80): ...
    async def eval(self, expression, await_promise=False): ...
    async def raw(self, method, params=None): ...
    async def go_back(self): ...
    async def go_forward(self): ...
    async def reload(self, ignore_cache=False): ...
    async def stop_loading(self): ...
    async def wait_for(self, strategy): ...
    async def pdf(self, params): ...
    async def screencast(self, params): ...
    async def list_tabs(self): ...
    async def new_tab(self, url="about:blank"): ...
    async def close_tab(self, tab_id): ...
    async def activate_tab(self, tab_id): ...
    async def capture_console(self, level="all"): ...
    async def capture_logs(self): ...
    async def dom_get(self, selector, outer=True): ...
    async def dom_query(self, selector, all=False): ...
    async def dom_set_attr(self, selector, name, value): ...
    async def dom_get_attr(self, selector, name): ...
    async def dom_remove_attr(self, selector, name): ...
    async def dom_remove(self, selector): ...
    async def dom_focus(self, selector): ...
    async def dom_scroll(self, selector=None, x=0, y=0): ...
    async def capture_har(self, params): ...
    async def get_cookies(self): ...
    async def set_cookie(self, params): ...
    async def delete_cookie(self, name, domain): ...
    async def clear_cookies(self): ...
    async def set_headers(self, headers): ...
    async def set_user_agent(self, user_agent): ...
    async def new_context(self): ...
    async def list_contexts(self): ...
    async def close_context(self, context_id): ...
    async def get_window_bounds(self): ...
    async def set_window_bounds(self, width, height, x=0, y=0): ...
    async def browser_version(self): ...
    async def emulate_device(self, device): ...
    async def set_viewport(self, width, height, device_scale_factor=1.0): ...
    async def set_geolocation(self, latitude, longitude, accuracy=100.0): ...
    async def set_timezone(self, timezone): ...
    async def set_dark_mode(self, enabled): ...
    async def click(self, selector, button="left", click_count=1): ...
    async def type_text(self, selector, text, delay=0): ...
    async def fill(self, selector, value): ...
    async def select_option(self, selector, value): ...
    async def hover(self, selector): ...
    async def key_press(self, key): ...
    async def drag(self, source, target): ...
    async def tap(self, selector): ...
    async def throttle_network(self, params): ...
    async def set_cache_disabled(self, disabled): ...
    async def block_requests(self, patterns): ...
    async def intercept_requests(self, handler): ...
    async def mock_response(self, url, response): ...
    async def intercept_download(self, url): ...
    async def a11y_tree(self): ...
    async def a11y_node(self, node_id): ...
    async def a11y_ancestors(self, node_id): ...
    async def dialog_accept(self, dialog_type="alert"): ...
    async def dialog_dismiss(self): ...
    async def grant_permission(self, permission): ...
    async def reset_permissions(self): ...
    async def get_security_state(self): ...
    async def ignore_cert_errors(self, ignore): ...
    async def set_locale(self, locale): ...
    async def set_cpu_throttle(self, rate): ...
    async def set_touch_emulation(self, enabled): ...
    async def set_sensors(self, sensors): ...
    async def perf_metrics(self): ...
    async def perf_trace(self, duration_ms=3000): ...
    async def perf_profile(self, duration_ms=3000): ...
    async def perf_heap_snapshot(self): ...
    async def perf_coverage(self): ...
    async def perf_css_coverage(self): ...
    async def css_get_styles(self, selector): ...
    async def css_get_stylesheets(self): ...
    async def css_get_rules(self, stylesheet_id): ...
    async def css_get_computed(self, selector): ...
    async def debug_set_breakpoint(self, url, line, condition=None): ...
    async def debug_set_breakpoint_function(self, function_name): ...
    async def debug_remove_breakpoint(self, breakpoint_id): ...
    async def debug_step_over(self): ...
    async def debug_step_into(self): ...
    async def debug_step_out(self): ...
    async def debug_pause(self): ...
    async def debug_resume(self): ...
    async def debug_get_listeners(self, selector): ...
    async def dom_snapshot(self): ...
    async def overlay_highlight(self, selector, color="rgba(255,0,0,0.5)"): ...
    async def overlay_clear(self): ...
    async def storage_get(self, key, storage_type="local"): ...
    async def storage_set(self, key, value, storage_type="local"): ...
    async def storage_clear(self, storage_type="local"): ...
    async def storage_list(self, storage_type="local"): ...
    async def cache_storage_list(self): ...
    async def cache_storage_entries(self, cache_name): ...
    async def cache_storage_delete(self, cache_name): ...
    async def indexeddb_list(self): ...
    async def indexeddb_get_data(self, database, store, key=""): ...
    async def indexeddb_clear(self, database, store): ...
    async def sw_list(self): ...
    async def sw_unregister(self, registration_id): ...
    async def sw_update(self, registration_id): ...
    async def animation_list(self): ...
    async def animation_pause(self, animation_id): ...
    async def animation_play(self, animation_id): ...
    async def animation_seek(self, animation_id, time_ms): ...
    async def webauthn_add_virtual_authenticator(self, protocol, transport): ...
    async def webauthn_remove_authenticator(self, authenticator_id): ...
    async def webauthn_add_credential(self, authenticator_id, credential): ...
    async def webauthn_get_credentials(self, authenticator_id): ...
    async def webaudio_get_contexts(self): ...
    async def webaudio_get_context(self, context_id): ...
    async def media_get_players(self): ...
    async def media_get_messages(self, player_id): ...
    async def cast_list(self): ...
    async def cast_start_tab(self, sink_name): ...
    async def cast_stop(self): ...
    async def bluetooth_emulate(self, name, address="00:00:00:00:00:01"): ...
    async def bluetooth_stop(self): ...


class TestBackendManager:
    """Tests for BackendManager."""

    def test_register_and_list(self):
        manager = BackendManager()
        manager.register("fake", FakeBackend)
        assert "fake" in manager.list_available()

    def test_create_registered(self):
        manager = BackendManager()
        manager.register("fake", FakeBackend)
        backend = manager.create("fake")
        assert isinstance(backend, FakeBackend)

    def test_create_unregistered_raises(self):
        manager = BackendManager()
        try:
            manager.create("nonexistent")
        except BackendNotSupportedError:
            pass
        else:
            raise AssertionError("Should have raised BackendNotSupportedError")

    def test_select_preferred(self):
        manager = BackendManager()
        manager.register("fake", FakeBackend)
        backend = manager.select("fake")
        assert isinstance(backend, FakeBackend)

    def test_select_fallback(self):
        manager = BackendManager()
        manager._registry.clear()
        manager.register("fake", FakeBackend)
        backend = manager.select(None)
        assert isinstance(backend, FakeBackend)

    def test_select_unavailable_preferred_raises(self):
        manager = BackendManager()
        manager.register("fake", FakeBackend)
        try:
            manager.select("nonexistent")
        except BackendNotAvailableError:
            pass
        else:
            raise AssertionError("Should have raised BackendNotAvailableError")
